version: "3.9"
services:
  backend:
    build: ./backend
    container_name: rpn_backend
    volumes:
      - ./backend/app/database.db:/app/app/database.db
    environment:
      - TZ=Europe/Paris
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: rpn_frontend
    depends_on:
      - backend
    ports:
      - "4040:80"
